services:
  - type: web
    name: kora-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: HF_EMBEDDING_MODEL
        value: sentence-transformers/distiluse-base-multilingual-cased
